
ENABLED_APPS = []

NEXT_ON_CONTROLLER_CHAIN = lambda *args, **kwargs: 0
NEXT_ON_MODEL_CHAIN      = lambda *args, **kwargs: 0

SENSORS_AUTOSTART = False
SENSORS_MODE = "TRANSFER"
SENSORS_LIST = []

CAMERA_AUTOSTART = False
CAMERA_COMMAND   = None
CAMERA_MODE      = "TRANSFER"

PHYSICAL_STATS_DELAY = 5.0
